server:
  port: 9999

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/molisting?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: 1111

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false #下划线转驼峰
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com:
      example:
        mapper:
          debug