server:
  port: 9999

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/molisting?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
    username: root
    password: 1111

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false #下划线转驼峰
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 日志打印输出
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com:
      example:
        mapper:
          debug

redis:
  host: localhost
  port: 6379
  jedis:
    pool:
      max-active: -1
      max-wait: 3000ms
  timeout: 3000ms